# 网站设置

# 导入主题
theme: jekyll-theme-chirpy

# 当你的网站是 Github Pages 并且没有自定义域名，修改其为"/项目名"。
baseurl: ''

# HTML 语言标签› https://www.w3.org/International/questions/qa-choosing-language-tags
lang: zh-CN

# 时区 › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: Nihil       # 主标题

tagline: 丑新罢了   # 副标题

description: >-                        # 由 seo meta 和 atom feed 使用
  Nichts Hsu的个人博客

# 填入你的网站的协议和域名，例如，'https://username.github.io'
url: 'https://nihil.cc'

author: Nichts Hsu    # 全名

github:
  username: NichtsVonChaos     # Github 用户名

twitter:
  username: Still_Nihil       # 推特用户名

social:
  name: Nichts Hsu                  # 将会显示为页脚处的版权所有者
  email: NichtsVonChaos@gmail.com             # 邮箱地址
  links:
    # 第一个链接将会作为版权所有者的链接
    - https://nihil.cc/
    - https://twitter.com/Still_Nihil      # 推特主页
    - https://github.com/NichtsVonChaos       # Github 主页
    # 取消注释以添加更多链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: dr-ktF8m84-3Bgb1D5faBkWAeXF_7FJYGuvyQFr9GXY # 改为你的 Google 认证字符串
# --------------------------

# 自定义 Iconfont 的图标代码。 › https://www.iconfont.cn/
# 需要添加自己的 Iconfont 图标，请在 Iconfont 中新建项目，
# 加入图标到项目，选择 Font Class，查看在线链接，并将其拷贝到下面的属性中。
#
# 注意：请不要与项目原本使用的图标重名，请全局搜索以确保该名称没被使用。
# 一个比较好的办法是修改 Iconfont 项目的 FontClass/Symbol 前缀为其他值。
#
# 当前 css 包含以 'icon-nihil-' 开头的图标，替换后这些图标不再可用，
# 但是以 'icon-' 开头的图标属于另一个 css，并不会失效。
iconfont_css: //at.alicdn.com/t/font_2451185_tgvgeuen2lh.css

google_analytics:
  id: 'G-RK9LRGVP0T'          # 填入你的 Google Analytics ID
  pv:
    # Google Analytics 页面浏览量开关
    # 不要启用它，除非你知道如何部署 Google Analytics superProxy
    enabled: false
    # 下面的设置仅在 `google_analytics.pv` 启用时生效
    proxy_url: ''
    proxy_endpoint: ''
    cache: false  # pv 数据本地缓存，对 GFW 区域的人而言很好

# Valine 评论系统
valine:
  comments: true    # 是否启用 Valine
  leancloud_appid: IpgOdqSXjwrACC2VyDICQNvv-MdYXbMMI    # 改为你的 LeanCloud App ID
  leancloud_appkey: NjP7uJ8rLW0NW8jYaTmtfNvh            # 改为你的 LeanCloud App Key
  placeholder: 说点什么吧！PS:在昵称栏输入QQ号可以自动获取QQ昵称和QQ头像哦~    # 空白评论框时显示的文字
  avatar: mp        # 默认头像  › https://valine.js.org/avatar.html 

# 设置首选配色方案
#
# 提示: 保留空白会跟随系统的默认首选配色，并且在侧边栏的底部会出现
# 一个可以转换亮色主题和暗色主题的按钮。
#
# 可用选项:
#
#     light  - 使用亮色方案
#     dark   - 使用暗色方案
#
theme_mode:   # [light|dark]

# 图像 CDN 端点。
# 注意一旦被分配，CDN 网址会被加在所有图像（网站头像和帖子图像）路径上。
#
# 例如，'https://cdn.com'
img_cdn: ''

# 侧边栏的头像，支持本地或 CROS 资源
avatar: /avatar.png

# 设置显示右侧边栏的内容
panel:
  # 设置显示在帖子中右侧边栏的内容
  # 
  # 提示:
  #   全局开关为false时必定不显示对应块。
  #   全局开关为true时，可以在帖子的 md 文件头部使用形如:
  #   lastmod: false
  #   的方式为该帖子单独关闭右侧边栏的功能。
  post:
    # 最近更新
    lastmod: false
    # 热门标签
    trending_tags: false
    # 外部链接
    external_links: false
    # 目录
    toc: true

# 每一页的帖子数量
paginate: 10

# 外部链接
external_links:
  -
    icon: https://img.shields.io/badge/link-996.icu-red.svg
    # 是否使用 Iconfont 的图标
    use_iconfont: false
    name: 996.icu
    # 为 true 时当且仅当图片无法加载时，使用名字替代。为 false 时始终显示名字。
    automatic_name: true
    link: https://996.icu
  -
    icon: icon-nihil-github
    use_iconfont: true
    name: 此博客的 Github 仓库
    automatic_name: false
    link: https://github.com/NichtsVonChaos/nichtsvonchaos.github.io
  # 在下面添加更多外部链接
  # -
  #   icon: 
  #   use_iconfont:
  #   name:
  #   automatic_name:
  #   link: 

# ------------ 下面的设置不建议修改 ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge 设置 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# 不要改变它除非你是 Jekyll 以及 Web 开发的专家，
# 或者你认为自己足够聪明可以在此模板中修改为其他的相对路径。
permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # 空字符串意味着项目里的所有文件
      type: posts
    values:
      layout: post
      comments: true    # 在帖子中启用评论
      # 右侧边栏的默认显示
      lastmod: true
      trending_tags: true
      external_links: true
      toc: true
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # 参考 `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # 在移动端隐藏标题

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
